name: YATRA UI Tests
permissions:
  contents: read

on:
  workflow_dispatch:


jobs:
  Yatra_UI_Tests:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Set up Python
        uses: actions/setup-python@v5
        with:
          python-version: '3.12'

      - name: Install Google Chrome
        run: |
          wget -q -O - https://dl-ssl.google.com/linux/linux_signing_key.pub | sudo apt-key add -
          sudo sh -c 'echo "deb [arch=amd64] http://dl.google.com/linux/chrome/deb/ stable main" >> /etc/apt/sources.list.d/google-chrome.list'
          sudo apt-get update
          sudo apt-get install -y google-chrome-stable

      - name: Install ChromeDriver
        run: |
          sudo apt-get install -y chromium-chromedriver
          sudo ln -s /usr/lib/chromium-browser/chromedriver /usr/bin/chromedriver || true

      - name: Install dependencies
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Run UI tests
        run: |
          pytest --headless tests/ --alluredir=allure-results
        continue-on-error: true

      - name: Generate Allure Report
        uses: simple-elf/allure-report-action@v1.7
        id: allure-report
        with:
          # The directory where the raw results from Step 4 are stored
          allure_results: allure-results
          # The directory where the final HTML report will be generated
          report_path: allure-report
          # Use a GitHub Pages branch to host the report (optional, but good practice)
          gh_pages: gh-pages

      - name: Archive raw Allure results
        uses: actions/upload-artifact@v4
        with:
          name: raw-allure-results
          path: allure-results

      - name: Upload Allure HTML Report
        uses: actions/upload-artifact@v4
        with:
          name: allure-html-report
          path: allure-report
          retention-days: 7